import { initializeApp } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-app.js";
import { getAuth, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-auth.js";
import { getFirestore, collection, query, where, getDocs } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-firestore.js";

const firebaseConfig = { apiKey:"AIzaSyCTz-YS4aaOS81XvDUFx3tiBISh0V7oUHo", authDomain:"rh-frb.firebaseapp.com", projectId:"rh-frb", storageBucket:"rh-frb.firebasestorage.app", messagingSenderId:"1069409309284", appId:"1:1069409309284:web:cac99c3a2457eef6a58571" };
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),state={user:null,days:[],expenses:[]};
const $=id=>document.getElementById(id), euro=v=>`${Number(v||0).toFixed(2).replace('.',',')} €`, dateLabel=v=>v?new Date(`${v}T12:00:00`).toLocaleDateString('fr-FR',{day:'2-digit',month:'2-digit',year:'numeric'}):'—';
function weekStart(){const d=new Date(),day=d.getDay()||7;d.setDate(d.getDate()-day+1);d.setHours(0,0,0,0);return d}function sameWeek(iso){const s=weekStart(),e=new Date(s);e.setDate(e.getDate()+7);const d=new Date(`${iso}T12:00:00`);return d>=s&&d<e}function toast(t){const e=$('toast');e.textContent=t;e.classList.add('visible');setTimeout(()=>e.classList.remove('visible'),2400)}
function render(){const week=state.days.filter(x=>sameWeek(x.date)),minutes=week.reduce((s,x)=>s+Number(x.totalMinutes||0),0),expenses=state.expenses.reduce((s,x)=>s+Number(x.amount||0),0);$('kpi-hours').textContent=`${Math.floor(minutes/60)}h ${String(minutes%60).padStart(2,'0')}`;$('kpi-days').textContent=week.length;$('kpi-expenses').textContent=euro(expenses);$('kpi-remaining').textContent=euro(Math.max(0,Number($('weekly-advance').value||0)-expenses));$('dashboard-entries').innerHTML=week.length?week.slice(0,8).map(x=>`<div class="list-item"><span>${dateLabel(x.date)} · ${x.mission||'Pointage'}</span><strong>${Math.floor(Number(x.totalMinutes||0)/60)}h${String(Number(x.totalMinutes||0)%60).padStart(2,'0')}</strong></div>`).join(''):'<p class="muted">Aucun pointage cette semaine.</p>';$('week-hours').textContent=`${Math.floor(minutes/60)}h ${String(minutes%60).padStart(2,'0')}`;const s=weekStart(),e=new Date(s);e.setDate(e.getDate()+6);$('week-range').textContent=`${dateLabel(s.toISOString().slice(0,10))} → ${dateLabel(e.toISOString().slice(0,10))}`;$('week-calendar').innerHTML=Array.from({length:7},(_,i)=>{const d=new Date(s);d.setDate(d.getDate()+i);const iso=d.toISOString().slice(0,10),x=state.days.find(y=>y.date===iso);return`<div class="calendar-cell ${x?'positive':''}"><small>${d.toLocaleDateString('fr-FR',{weekday:'short'})}</small><strong>${d.getDate()}</strong><span>${x?`${Math.floor(Number(x.totalMinutes||0)/60)}h${String(Number(x.totalMinutes||0)%60).padStart(2,'0')}`:'—'}</span></div>`}).join('');renderHistory();renderExpenses()}
function renderHistory(){$('timesheet-history').innerHTML=state.days.length?state.days.map(x=>`<div class="list-item"><span><strong>${dateLabel(x.date)}</strong><br><small>${x.morningStart||'--:--'} / ${x.morningEnd||'--:--'} · ${x.afternoonStart||'--:--'} / ${x.dayEnd||'--:--'}<br>${x.mission||'Sans mission'} · ${x.zone||'Zone non renseignée'} · ${x.team||'Équipe non renseignée'} · ${x.car||'Voiture non renseignée'} · ${x.assignment||'Affectation non renseignée'}</small></span><strong>${Math.floor(Number(x.totalMinutes||0)/60)}h</strong></div>`).join(''):'<p class="muted">Aucun pointage enregistré.</p>'}function renderExpenses(){$('expense-total').textContent=euro(state.expenses.reduce((s,x)=>s+Number(x.amount||0),0));$('expense-list').innerHTML=state.expenses.length?state.expenses.map(x=>`<div class="list-item"><span>${dateLabel(x.date)} · ${x.category||'Autre'}<br><small>${x.description||''}</small></span><strong>${euro(x.amount)}</strong></div>`).join(''):'<p class="muted">Aucune note de frais synchronisée.</p>'}
async function load(){if(!state.user)return;const q=query(collection(db,'timesheets'),where('uid','==',state.user.uid)),s=await getDocs(q);state.days=s.docs.map(x=>({id:x.id,...x.data()}));try{const e=await getDocs(collection(db,'users',state.user.uid,'expenses'));state.expenses=e.docs.map(x=>({id:x.id,...x.data()}))}catch{}render()}
function nav(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.screen').forEach(x=>x.classList.toggle('active',x.id===`view-${b.dataset.view}`))});document.querySelectorAll('[data-view-link]').forEach(b=>b.onclick=()=>document.querySelector(`[data-view="${b.dataset.viewLink}"]`).click())}
function init(){nav();$('month-picker').value=new Date().toISOString().slice(0,7);$('weekly-target').oninput=render;$('weekly-advance').oninput=render;$('expense-form').onsubmit=e=>{e.preventDefault();state.expenses.push({date:$('expense-date').value,category:$('expense-category').value,amount:Number($('expense-amount').value),description:$('expense-description').value});e.target.reset();render();toast('Note de frais ajoutée localement.');};onAuthStateChanged(auth,u=>{state.user=u;$('auth-status').textContent=u?u.email:'Non connecté';if(u)load()})}init();